InferenceEngineClient initialized with 2 engines.
Total steps: 35
Validation set size: 1
2025-07-25 06:40:19.805 | INFO     | skyrl_train.workers.worker:_initiate_actors:543 - Initializing process group for RayActorGroup
2025-07-25 06:40:28.130 | INFO     | skyrl_train.workers.worker:_initiate_actors:545 - Initialized process group for RayActorGroup
2025-07-25 06:40:28.146 | INFO     | skyrl_train.workers.worker:_initiate_actors:547 - Mesh Ranks: [MeshRank(dp=0, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=1, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=2, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=3, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=4, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=5, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=6, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=7, sp=0, tp=0, world_size=8, dp_size=8)]
2025-07-25 06:40:35.513 | INFO     | skyrl_train.workers.worker:_initiate_actors:543 - Initializing process group for RayActorGroup
2025-07-25 06:40:43.805 | INFO     | skyrl_train.workers.worker:_initiate_actors:545 - Initialized process group for RayActorGroup
2025-07-25 06:40:43.820 | INFO     | skyrl_train.workers.worker:_initiate_actors:547 - Mesh Ranks: [MeshRank(dp=0, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=1, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=2, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=3, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=4, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=5, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=6, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=7, sp=0, tp=0, world_size=8, dp_size=8)]
Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): [36mray::FSDPRefRayActorBase.init_model()[39m (pid=2315129, ip=240.25.216.128, actor_id=3a8fbad0e403e59475f8732901000000, repr=<skyrl_train.workers.fsdp.fsdp_worker.FSDPRefRayActorBase object at 0x78131f920770>)
  File "/root/miniconda3/envs/ctu/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/ctu/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/CTU-Agent-v0/SkyRL_mod/skyrl-train/skyrl_train/workers/fsdp/fsdp_worker.py", line 371, in init_model
    model = Actor(
            ^^^^^^
  File "/root/CTU-Agent-v0/SkyRL_mod/skyrl-train/skyrl_train/models.py", line 72, in __init__
    assert self.use_flash_attention_2, "Flash attention 2 should be used for `use_sample_packing`"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Flash attention 2 should be used for `use_sample_packing`
